export interface Service {
  slug: string;
  shortTitle: string;
  title: string;
  heroHeadline: string;
  subheadline: string;
  icon: string;
  description: string;
  metaTitle: string;
  metaDescription: string;
  problemPoints: { title: string; description: string }[];
  approach: { step: string; title: string; description: string }[];
  deliverables: string[];
  faq: { question: string; answer: string }[];
  relatedCaseStudySlugs: string[];
}

export const services: Service[] = [
  {
    slug: "meta-ads",
    shortTitle: "Meta Ads",
    title: "Meta Ads Management",
    heroHeadline: "Profitable Meta Ads That Scale Your D2C Brand",
    subheadline: "Stop burning budget on ads that don't convert. We build data-driven Meta campaigns that drive consistent revenue growth for D2C brands.",
    icon: "Target",
    description: "We create and manage high-performance Meta advertising campaigns specifically designed for D2C ecommerce brands.",
    metaTitle: "Meta Ads Management for D2C Brands | Growth Escalators",
    metaDescription: "Profitable Meta Ads campaigns for D2C ecommerce brands. Specializing in Facebook & Instagram advertising with proven ROAS.",
    problemPoints: [
      { title: "Bleeding Ad Budget", description: "Most brands run broad targeting campaigns that waste 60-80% of their budget on unqualified audiences." },
      { title: "Inconsistent ROAS", description: "Results fluctuate wildly month to month, making revenue planning impossible." },
      { title: "Creative Fatigue", description: "The same creatives running for months cause audience fatigue and skyrocketing CPMs." },
      { title: "No Attribution Clarity", description: "Not knowing which campaigns actually drive revenue leads to poor budget allocation decisions." },
    ],
    approach: [
      { step: "01", title: "Audit & Research", description: "Deep dive into your existing account, audience data, and competitor landscape." },
      { step: "02", title: "Strategy Build", description: "Custom funnel architecture with awareness, consideration, and conversion campaigns." },
      { step: "03", title: "Creative Testing", description: "Systematic A/B testing of hooks, formats, and offers to find winning creatives." },
      { step: "04", title: "Scale & Optimize", description: "Incrementally scale winning campaigns while maintaining target ROAS." },
      { step: "05", title: "Report & Iterate", description: "Weekly performance reviews with clear data and actionable next steps." },
    ],
    deliverables: [
      "Full Meta Ads account setup & structure",
      "Audience research and targeting strategy",
      "Campaign creation and management",
      "Weekly creative testing framework",
      "Pixel & conversion tracking setup",
      "Weekly performance reports",
      "Monthly strategy review calls",
      "Retargeting & lookalike audience management",
    ],
    faq: [
      { question: "What's the minimum ad spend you work with?", answer: "We typically work with brands spending a minimum of ₹1 lakh/month on ad spend. This ensures enough data to optimize properly." },
      { question: "How long before we see results?", answer: "Most brands see meaningful improvements within 4-6 weeks as we gather data and optimize. Significant scale typically happens in months 2-3." },
      { question: "Do you handle creative production?", answer: "We provide creative strategy and direction. We work with your existing creatives or can connect you with our creative team for production." },
      { question: "What ROAS can we expect?", answer: "ROAS varies by industry, product, and price point. We target a ROAS that makes your business profitable after accounting for all costs." },
    ],
    relatedCaseStudySlugs: ["odra-organics", "paraizo"],
  },
  {
    slug: "google-ads",
    shortTitle: "Google Ads",
    title: "Google Ads Management",
    heroHeadline: "Capture High-Intent Buyers With Google Ads",
    subheadline: "Reach customers who are actively searching for products like yours. We build Google Shopping and Search campaigns that drive profitable revenue.",
    icon: "Search",
    description: "Strategic Google Ads management covering Search, Shopping, and Performance Max campaigns for D2C brands.",
    metaTitle: "Google Ads Management for D2C Brands | Growth Escalators",
    metaDescription: "Drive high-intent traffic and sales with Google Ads. Expert Google Shopping and Search campaign management for D2C ecommerce.",
    problemPoints: [
      { title: "Wasted Spend on Wrong Keywords", description: "Broad match keywords eating budget on irrelevant searches with no conversion potential." },
      { title: "Poor Shopping Feed Quality", description: "Unoptimized product feeds leading to poor ad rank and low click-through rates." },
      { title: "No Smart Bidding Strategy", description: "Manual bidding limiting growth potential and missing high-value conversion opportunities." },
      { title: "Overlooking Brand Campaigns", description: "Not protecting brand terms means competitors steal your existing demand." },
    ],
    approach: [
      { step: "01", title: "Account Audit", description: "Comprehensive review of existing campaigns, keywords, and conversion tracking." },
      { step: "02", title: "Feed Optimization", description: "Optimize your product feed for maximum Shopping campaign performance." },
      { step: "03", title: "Campaign Architecture", description: "Build structured campaigns with proper ad groups, match types, and negatives." },
      { step: "04", title: "Bid Strategy", description: "Implement smart bidding strategies aligned with your profitability targets." },
      { step: "05", title: "Continuous Optimization", description: "Regular search term reviews, bid adjustments, and performance analysis." },
    ],
    deliverables: [
      "Full Google Ads account audit & restructure",
      "Google Shopping & Performance Max setup",
      "Search campaign with keyword research",
      "Merchant Center optimization",
      "Conversion tracking implementation",
      "Negative keyword management",
      "Weekly performance reports",
      "Monthly strategy reviews",
    ],
    faq: [
      { question: "Do you manage Google Shopping specifically?", answer: "Yes, Google Shopping and Performance Max are our primary focus for D2C brands as they drive the highest purchase intent." },
      { question: "Do we need a separate agency for Google vs Meta?", answer: "We manage both channels together for better attribution and budget allocation across the full customer journey." },
      { question: "How does Google Ads differ from Meta Ads?", answer: "Google captures existing demand (people searching for your product), while Meta creates demand by reaching cold audiences. Both are essential for scale." },
      { question: "What's the setup timeline?", answer: "Account audit and campaign setup typically takes 1-2 weeks. We start seeing performance data within 30 days." },
    ],
    relatedCaseStudySlugs: ["paraizo", "swarnsootra"],
  },
  {
    slug: "cro",
    shortTitle: "CRO",
    title: "Conversion Rate Optimization",
    heroHeadline: "Convert More Visitors Into Buyers Without More Ad Spend",
    subheadline: "Increasing your conversion rate from 1% to 2% effectively doubles your revenue from the same traffic. We find and fix what's stopping customers from buying.",
    icon: "TrendingUp",
    description: "Data-driven CRO services that improve your store's conversion rate through systematic testing and UX optimization.",
    metaTitle: "CRO Services for D2C Ecommerce | Growth Escalators",
    metaDescription: "Increase your Shopify store's conversion rate with proven CRO strategies. Data-driven testing that turns more visitors into buyers.",
    problemPoints: [
      { title: "Low Conversion Rate", description: "Sending traffic to a store that converts at 0.5-1% means 99% of your ad spend goes to waste." },
      { title: "High Cart Abandonment", description: "Customers adding to cart but not completing purchase — often fixable with checkout optimization." },
      { title: "Poor Mobile Experience", description: "70%+ of traffic is mobile but most stores are designed for desktop first." },
      { title: "Trust Deficit", description: "Visitors don't feel confident enough to buy from a brand they've never heard of." },
    ],
    approach: [
      { step: "01", title: "CRO Audit", description: "Analyze heatmaps, session recordings, and funnel data to identify drop-off points." },
      { step: "02", title: "Research", description: "Customer surveys, exit polls, and competitor benchmarking to understand objections." },
      { step: "03", title: "Hypothesis", description: "Build prioritized testing roadmap based on impact vs effort scoring." },
      { step: "04", title: "A/B Testing", description: "Run controlled experiments on landing pages, PDPs, and checkout flow." },
      { step: "05", title: "Implement & Iterate", description: "Roll out winners and continue testing for compound conversion improvements." },
    ],
    deliverables: [
      "Full CRO audit report with findings",
      "Heatmap & session recording analysis",
      "A/B testing implementation",
      "Landing page optimization",
      "Product page optimization",
      "Checkout flow improvements",
      "Mobile UX optimization",
      "Monthly CRO report with test results",
    ],
    faq: [
      { question: "How much traffic do we need for CRO?", answer: "A minimum of 5,000 monthly sessions is ideal for meaningful A/B test results. Smaller stores can still benefit from CRO audits and best practice implementation." },
      { question: "Do you work with Shopify?", answer: "Yes, Shopify is our primary platform. We also work with WooCommerce and custom builds." },
      { question: "What's a realistic conversion rate improvement?", answer: "Most brands see 20-40% improvement in conversion rate within 90 days of systematic CRO work." },
      { question: "Do you redesign the whole website?", answer: "We make targeted, data-driven changes rather than full redesigns. This minimizes risk and allows us to measure the impact of each change." },
    ],
    relatedCaseStudySlugs: ["odra-organics", "atatika-studios"],
  },
  {
    slug: "creative-strategy",
    shortTitle: "Creative Strategy",
    title: "Creative Strategy & Production",
    heroHeadline: "Creatives That Stop the Scroll and Drive Purchases",
    subheadline: "In a world where everyone is running the same generic ads, breakthrough creative is your biggest competitive advantage.",
    icon: "Palette",
    description: "Strategic ad creative development — from concept to production — designed to perform in Meta and Google ecosystems.",
    metaTitle: "Ad Creative Strategy for D2C Brands | Growth Escalators",
    metaDescription: "Stop-the-scroll ad creatives for D2C brands. Strategic creative development that drives results on Meta and Google.",
    problemPoints: [
      { title: "Generic Creative Doesn't Convert", description: "Stock photos and basic product shots don't build trust or create desire in cold audiences." },
      { title: "No Testing Framework", description: "Running the same 2-3 creatives without systematic testing leaves major performance on the table." },
      { title: "No Message-Market Fit", description: "Ads that don't speak to the specific pain points of your target customer fall flat." },
      { title: "Creative Fatigue Killing ROAS", description: "Without fresh creative, frequency rises, CPMs skyrocket, and ROAS crashes." },
    ],
    approach: [
      { step: "01", title: "Brand Deep-Dive", description: "Understand your brand voice, target customer, key differentiators, and competitor creative landscape." },
      { step: "02", title: "Creative Brief", description: "Develop detailed briefs with hooks, scripts, visual direction, and key messaging." },
      { step: "03", title: "Production", description: "Execute static, video, and UGC-style content designed for paid social performance." },
      { step: "04", title: "Launch & Test", description: "Systematic launch with proper naming conventions for organized performance tracking." },
      { step: "05", title: "Analyze & Iterate", description: "Identify winning patterns and double down on what works while retiring losers." },
    ],
    deliverables: [
      "Monthly creative strategy briefs",
      "Static ad creatives (various formats)",
      "Video ad scripts & storyboards",
      "UGC-style content direction",
      "Creative testing framework",
      "Ad copy variations",
      "Carousel and collection ads",
      "Creative performance analysis",
    ],
    faq: [
      { question: "Do you produce the videos?", answer: "We provide scripts, storyboards, and creative direction. For production, we can coordinate with your in-house team or our network of creators." },
      { question: "How many creatives per month?", answer: "Typically 8-12 new creative variations per month to maintain a healthy testing pipeline." },
      { question: "What formats do you create?", answer: "We create for all placements: Feed, Stories, Reels, Carousels, and Collection ads in both 1:1, 4:5, and 9:16 ratios." },
      { question: "Can you work with our brand guidelines?", answer: "Absolutely. We work within your brand guidelines while optimizing for ad performance." },
    ],
    relatedCaseStudySlugs: ["odra-organics", "paraizo"],
  },
  {
    slug: "funnels-automation",
    shortTitle: "Funnels & Automation",
    title: "Sales Funnels & Marketing Automation",
    heroHeadline: "Build Revenue Machines That Work While You Sleep",
    subheadline: "A properly built funnel and automation stack can increase revenue by 30-50% without additional ad spend through better lead nurturing and customer retention.",
    icon: "Workflow",
    description: "End-to-end sales funnel design and marketing automation for D2C brands looking to maximize lifetime customer value.",
    metaTitle: "Sales Funnels & Marketing Automation | Growth Escalators",
    metaDescription: "Build automated sales funnels that nurture leads and maximize customer lifetime value for D2C ecommerce brands.",
    problemPoints: [
      { title: "Leaky Funnels", description: "Leads entering your funnel but never converting because there's no nurture sequence in place." },
      { title: "No Post-Purchase System", description: "Acquiring a customer and then forgetting about them — missing massive LTV potential." },
      { title: "Manual Follow-Up", description: "Your team spending hours on manual tasks that should be fully automated." },
      { title: "No Segmentation", description: "Sending the same message to all customers regardless of their behavior or purchase history." },
    ],
    approach: [
      { step: "01", title: "Funnel Mapping", description: "Map your complete customer journey from first touch to repeat purchase." },
      { step: "02", title: "Tool Setup", description: "Configure the right automation tools (Klaviyo, ActiveCampaign, etc.) for your stack." },
      { step: "03", title: "Sequence Build", description: "Build email and SMS sequences for welcome, abandon cart, post-purchase, and winback." },
      { step: "04", title: "Segmentation", description: "Implement behavioral and purchase-based segmentation for personalized messaging." },
      { step: "05", title: "Optimize & Scale", description: "A/B test subject lines, timing, and offers to continuously improve automation performance." },
    ],
    deliverables: [
      "Full funnel audit and mapping",
      "Email automation sequences (Welcome, Abandon Cart, Post-Purchase, Winback)",
      "SMS automation setup",
      "Customer segmentation strategy",
      "Lead capture optimization",
      "CRM setup and configuration",
      "Performance dashboards",
      "Monthly automation report",
    ],
    faq: [
      { question: "Which email platform do you use?", answer: "We primarily work with Klaviyo for ecommerce as it has the best Shopify integration. We also work with ActiveCampaign and Mailchimp." },
      { question: "What's a typical abandon cart recovery rate?", answer: "A well-optimized abandon cart sequence typically recovers 5-15% of abandoned carts, representing significant revenue." },
      { question: "How long to set up the full automation?", answer: "Core automation setup (welcome, abandon cart, post-purchase) typically takes 3-4 weeks." },
      { question: "Do you manage email campaigns too?", answer: "Yes, we can manage both automated flows and regular campaign sends as part of a full email marketing retainer." },
    ],
    relatedCaseStudySlugs: ["paraizo", "atatika-studios"],
  },
  {
    slug: "ecommerce-marketing",
    shortTitle: "Ecommerce Marketing",
    title: "Full-Stack Ecommerce Marketing",
    heroHeadline: "Complete Ecommerce Growth System for D2C Brands",
    subheadline: "From traffic acquisition to retention, we build and manage your entire ecommerce marketing engine for predictable, profitable growth.",
    icon: "ShoppingBag",
    description: "Comprehensive ecommerce marketing management covering paid media, email, CRO, and analytics for D2C brands.",
    metaTitle: "Ecommerce Marketing Agency for D2C | Growth Escalators",
    metaDescription: "Full-stack ecommerce marketing for D2C brands. Meta Ads, Google Ads, Email, CRO, and Analytics under one roof.",
    problemPoints: [
      { title: "Fragmented Marketing", description: "Working with multiple agencies who don't talk to each other creates strategy gaps and attribution confusion." },
      { title: "Over-Reliance on One Channel", description: "Brands that only run Meta Ads are one algorithm change away from catastrophe." },
      { title: "No Unified Analytics", description: "Without a single view of your marketing data, you can't make informed budget decisions." },
      { title: "Growth Plateaus", description: "Hitting a revenue ceiling because no one is looking at the full picture and identifying new growth levers." },
    ],
    approach: [
      { step: "01", title: "Growth Audit", description: "Comprehensive audit of all marketing channels, analytics, and growth opportunities." },
      { step: "02", title: "Strategy", description: "Build a unified growth strategy with clear channel allocation and milestones." },
      { step: "03", title: "Execute", description: "Implement across Meta, Google, Email, and CRO with a coordinated approach." },
      { step: "04", title: "Measure", description: "Unified reporting dashboard giving you a single view of all marketing performance." },
      { step: "05", title: "Scale", description: "Identify winning channels and scale them while maintaining profitability targets." },
    ],
    deliverables: [
      "Full ecommerce growth audit",
      "Unified marketing strategy",
      "Meta & Google Ads management",
      "Email & SMS marketing",
      "CRO implementation",
      "Analytics & attribution setup",
      "Unified reporting dashboard",
      "Monthly strategy review",
    ],
    faq: [
      { question: "Is this a full outsourcing model?", answer: "Yes, we act as your complete growth team. You get a dedicated account manager plus specialists in each channel." },
      { question: "Minimum revenue to qualify?", answer: "We typically work with brands doing ₹5L+ monthly revenue who are ready to invest in proper growth infrastructure." },
      { question: "How do you coordinate across channels?", answer: "We have weekly cross-channel reviews to ensure all channels are working together and budgets are allocated to the highest performers." },
      { question: "What's the contract length?", answer: "We work on 3-month minimum contracts as meaningful results take time. Most clients continue for 12+ months." },
    ],
    relatedCaseStudySlugs: ["odra-organics", "swarnsootra"],
  },
  {
    slug: "website-development",
    shortTitle: "Website Development",
    title: "High-Converting Website Development",
    heroHeadline: "Websites Built to Convert, Not Just Look Good",
    subheadline: "Your website is your most important sales asset. We build fast, conversion-optimized websites that turn visitors into customers.",
    icon: "Code",
    description: "Performance-focused website development for D2C brands — Shopify stores, landing pages, and custom web builds.",
    metaTitle: "Website Development for D2C Brands | Growth Escalators",
    metaDescription: "High-converting website development for D2C ecommerce. Shopify store design, landing pages, and conversion optimization.",
    problemPoints: [
      { title: "Slow Loading Speed", description: "Every second of load time reduces conversions by 7%. Most brand websites take 5+ seconds to load." },
      { title: "Poor Mobile Experience", description: "Sites not optimized for mobile miss the majority of ecommerce traffic and conversions." },
      { title: "No Conversion Architecture", description: "Beautiful sites that aren't structured to guide visitors toward purchase decisions." },
      { title: "DIY Shopify Themes", description: "Generic themes that don't differentiate your brand or optimize for your specific products." },
    ],
    approach: [
      { step: "01", title: "Discovery", description: "Understand your brand, products, target customer, and conversion goals." },
      { step: "02", title: "Wireframe", description: "Create conversion-optimized page layouts before any design work begins." },
      { step: "03", title: "Design", description: "Build high-fidelity designs that balance brand aesthetics with conversion principles." },
      { step: "04", title: "Develop", description: "Build the site with performance, SEO, and conversion optimization built in from the start." },
      { step: "05", title: "Launch & Optimize", description: "Launch with proper analytics tracking and begin CRO optimization immediately." },
    ],
    deliverables: [
      "Custom Shopify store design & development",
      "Mobile-first responsive design",
      "Page speed optimization",
      "Conversion-optimized product pages",
      "Landing page design & development",
      "Analytics & pixel setup",
      "SEO technical foundation",
      "3-month post-launch support",
    ],
    faq: [
      { question: "Do you build on Shopify?", answer: "Yes, Shopify is our primary platform. We also build on WooCommerce and can develop custom landing pages on any stack." },
      { question: "What's a typical project timeline?", answer: "A full Shopify store typically takes 4-6 weeks from kickoff to launch. Landing pages can be done in 1-2 weeks." },
      { question: "Do you handle Shopify apps & integrations?", answer: "Yes, we set up all required apps (reviews, upsell, loyalty, email) and integrate them with your marketing stack." },
      { question: "What happens after launch?", answer: "We provide 3 months of post-launch support and then transition to our CRO retainer for ongoing optimization." },
    ],
    relatedCaseStudySlugs: ["atatika-studios", "odra-organics"],
  },
];
